#!/usr/bin/env bash

echo "downloading flair models"
python3 -c "from flair.models import SequenceTagger as s;s.load('ner')"
python3 -c "from flair.models import SequenceTagger as s;s.load('ner-ontonotes')"
python3 -c "from flair.models import SequenceTagger as s;s.load('pos')"
python3 -c "from flair.models import SequenceTagger as s;s.load('frame')"
python3 -c "from flair.models import SequenceTagger as s;s.load('chunk')"
python3 -c "from flair.models import SequenceTagger as s;s.load('ner-fast')"
python3 -c "from flair.models import SequenceTagger as s;s.load('ner-ontonotes-fast')"
python3 -c "from flair.models import SequenceTagger as s;s.load('pos-fast')"
python3 -c "from flair.models import SequenceTagger as s;s.load('frame-fast')"
python3 -c "from flair.models import SequenceTagger as s;s.load('chunk-fast')"
python3 -c "from flair.models import SequenceTagger as s;s.load('ner-multi')"
python3 -c "from flair.models import SequenceTagger as s;s.load('ner-multi-fast')"
python3 -c "from flair.models import SequenceTagger as s;s.load('pos-multi')"
python3 -c "from flair.models import SequenceTagger as s;s.load('pos-multi-fast')"
python3 -c "from flair.models import SequenceTagger as s;s.load('pos-multi-fast-learn')"
python3 -c "from flair.models import SequenceTagger as s;s.load('de-ner')"
python3 -c "from flair.models import SequenceTagger as s;s.load('de-pos')"
python3 -c "from flair.models import SequenceTagger as s;s.load('de-pos-fine-grained')"
python3 -c "from flair.models import SequenceTagger as s;s.load('fr-ner')"
python3 -c "from flair.models import SequenceTagger as s;s.load('nl-ner')"
python3 -c "from flair.models import TextClassifier as s;s.load('en-sentiment')"
python3 -c "from flair.models import TextClassifier as s;s.load('de-offensive-language')"
python3 -c "from flair.embeddings import CharacterEmbeddings as s;s()"
python3 -c "from flair.embeddings import BytePairEmbeddings as s;s('en')"
python3 -c "from flair.embeddings import WordEmbeddings as s;s('glove')"
python3 -c "from flair.embeddings import FlairEmbeddings as s;s('multi-forward')"
python3 -c "from flair.embeddings import FlairEmbeddings as s;s('multi-backward')"
python3 -c "from flair.embeddings import FlairEmbeddings as s;s('news-forward')"
python3 -c "from flair.embeddings import FlairEmbeddings as s;s('news-backward')"
python3 -c "from flair.embeddings import FlairEmbeddings as s;s('news-forward-fast')"
python3 -c "from flair.embeddings import FlairEmbeddings as s;s('news-backward-fast')"
python3 -c "from flair.embeddings import FlairEmbeddings as s;s('multi-forward-fast')"
python3 -c "from flair.embeddings import FlairEmbeddings as s;s('multi-backward-fast')"
python3 -c "from flair.embeddings import FlairEmbeddings as s;s('mix-forward')"
python3 -c "from flair.embeddings import FlairEmbeddings as s;s('mix-backward')"
